// Code generated by sqlc. DO NOT EDIT.

import { type Client } from "@libsql/client";

export const getAuthorQuery = `-- name: GetAuthor :one
SELECT id, name, bio_graphyitis
FROM authors
WHERE id = ?
LIMIT 1`;

export interface GetAuthorArgs {
    id: number;
}

export interface GetAuthorRow {
    id: number;
    name: string;
    bio_graphyitis: string | null;
}

export async function getAuthor(database: Client, args: GetAuthorArgs): Promise<GetAuthorRow | null> {
    const ret = await database.execute({
        sql: getAuthorQuery,
        args: [args.id]
    });
    if (ret.rows.length === 0) {
        return null;
    }
    if (ret.rows.length > 1) {
        throw new Error("violated single-row constraint in query [getAuthorQuery], expected 1 got " + ret.rows.length);
    }
    const result = ret.rows[0];
    return result as unknown as GetAuthorRow;
}

export const listAuthorsQuery = `-- name: ListAuthors :many
SELECT id, name, bio_graphyitis
FROM authors
ORDER BY name`;

export interface ListAuthorsRow {
    id: number;
    name: string;
    bio_graphyitis: string | null;
}

export async function listAuthors(database: Client): Promise<ListAuthorsRow[]> {
    const result = await database.execute({
        sql: listAuthorsQuery,
        args: []
    });
    return result.rows as unknown as ListAuthorsRow[];
}

export const createAuthorQuery = `-- name: CreateAuthor :exec
INSERT INTO authors (name, bio_graphyitis)
VALUES (?, ?)`;

export interface CreateAuthorArgs {
    name: string;
    bio_graphyitis: string | null;
}

export async function createAuthor(database: Client, args: CreateAuthorArgs): Promise<number> {
    const ret = await database.execute({
        sql: createAuthorQuery,
        args: [args.name, args.bio_graphyitis]
    });
    return ret.rowsAffected;
}

export const deleteAuthorQuery = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = ?`;

export interface DeleteAuthorArgs {
    id: number;
}

export async function deleteAuthor(database: Client, args: DeleteAuthorArgs): Promise<number> {
    const ret = await database.execute({
        sql: deleteAuthorQuery,
        args: [args.id]
    });
    return ret.rowsAffected;
}

